apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "amp.fullname" . }}
  labels:
    release: {{ .Release.Name }}
    app: {{ include "amp.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "amp.name" . }}
      release: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
